/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnicaRouteImport } from './routes/tecnica'
import { Route as CriminalisticaRouteImport } from './routes/criminalistica'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const TecnicaRoute = TecnicaRouteImport.update({
  id: '/tecnica',
  path: '/tecnica',
  getParentRoute: () => rootRouteImport,
} as any)
const CriminalisticaRoute = CriminalisticaRouteImport.update({
  id: '/criminalistica',
  path: '/criminalistica',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/criminalistica': typeof CriminalisticaRoute
  '/tecnica': typeof TecnicaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/criminalistica': typeof CriminalisticaRoute
  '/tecnica': typeof TecnicaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/criminalistica': typeof CriminalisticaRoute
  '/tecnica': typeof TecnicaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/criminalistica' | '/tecnica'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/criminalistica' | '/tecnica'
  id: '__root__' | '/' | '/contacto' | '/criminalistica' | '/tecnica'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  CriminalisticaRoute: typeof CriminalisticaRoute
  TecnicaRoute: typeof TecnicaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnica': {
      id: '/tecnica'
      path: '/tecnica'
      fullPath: '/tecnica'
      preLoaderRoute: typeof TecnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criminalistica': {
      id: '/criminalistica'
      path: '/criminalistica'
      fullPath: '/criminalistica'
      preLoaderRoute: typeof CriminalisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  CriminalisticaRoute: CriminalisticaRoute,
  TecnicaRoute: TecnicaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
